from typing import Dict, List
from .base import BaseLLMClient


class MockLLMClient(BaseLLMClient):
    """
    本地演示用 Mock LLM。
    真实接入 Mimo 时，替换为 MimoClient。
    """

    def chat(self, system: str, messages: List[Dict[str, str]], temperature: float = 0.2) -> str:
        last = messages[-1]["content"] if messages else ""
        return (
            "Mock response generated by EduAgent system.\n"
            f"System role: {system[:80]}...\n"
            f"Input preview: {last[:160]}..."
        )
